name: COM_Zombies
main: com.zombies.COMZombiesMain
authors: [Turkey2349, stormbot28]
description: "SWROTR: Call Of Minecraft: Zombies!"
version: 1.3.0
load: POSTWORLD
softdepend: [Vault]
commands:
  zombies:
    description: "Type /zombies help for more info!"
    aliases: [z, zo, zom, zombie, comz, codz]